---
title: "Personal Final Assessment"
subtitle: "STT2860 S22 Project 03"
author: "Authors: Phu Tran"
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---
***

This is a free-form reflection about your experience in the course. Pleased wait to complete these questions until after you finish (or mostly finish) Project #3.

**Question 1:** Reflect back on your experience in this course. What accomplishment(s) are you most proud of?

ANSWER: I'm proud of completing the Datacamp courses because of my experience with coding back at UNC Charlotte. I like that the pace of this course is slow because it gives me time to do the problems. If I have any trouble on a problem, I go back and rewatch the video to see what I did wrong. 

**Question 2:** What topic(s) do you still find yourself struggling with? What materials, resources, or help do you feel you would need to help clear up this topic?

ANSWER: I struggled with the commands within a code, specifically the graphs commands. I know how to do use it, it's just not giving me the result I wanted. The resources I used were the notes, classworks, and Datacamp to find the command. 

**Question 3:** If you could go back to the start of the semester and do things over, what (if anything) would you change about your approach to this course?

ANSWER: I honestly need to practice some more coding if I need to start over. I know it will be overwhelming, but if the pace is slow, I'll be fine. 

**Question 4:** Consider the "Becoming a Data Scientist" interviews you watched for the first two projects. Do you consider *yourself* a data scientist? Please explain.

ANSWER: I think I consider myself a Data Scientist because we're looking at important data. The best example would be COVID cases in certain countries. For example, let's take the United States and look at how COVID is spreading throughout the country. The CDC will look at what precautionary measures we need to do to stop the spread. I took a statistics class at a community college and we have to explain why the COVID data is really important. I said that we need this data to figure out how to minimize the spread of COVID by quarantine and wear face coverings. If the spread slows down, we can go back to normal life, but still be cautious of COVID. 

***